### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by vedantterse** [vedantterse/StonePapperScissor#2]
![image](https://github.com/vedantterse/StonePapperScissor/assets/69134828/7b274d31-ebad-476b-9808-44316b8ddb5f)
at this stage when users enters anything other than yes it counts to be break the loop

![image](https://github.com/vedantterse/StonePapperScissor/assets/69134828/e70215c3-ba8a-4fa1-af08-e27ba9739924)
fix this so that it can only exit when the value is given "no" and other than this value should throw an error

**Comment by ankman007** [comment]
@vedantterse Working on this issue. Please assign it to me.

**Comment by Tashuuuu** [comment]
Is the issue still open?

**Comment by vedantterse** [comment]
> Is the issue still open?

yes, it is!!
